# Generated by Django 3.2.4 on 2021-06-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='color',
            field=models.CharField(default='white', max_length=10),
            preserve_default=False,
        ),
    ]
