# Generated by Django 3.2.4 on 2021-07-01 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_projecttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.projecttype'),
        ),
    ]
