# Generated by Django 3.2.4 on 2021-07-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project_project_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_type',
            new_name='type',
        ),
    ]
